spring:
  application:
    name: encurtador-url

  data:
    redis:
      host: localhost
      port: 6379
    
  cache:
    type: redis
    redis:
      time-to-live: 5m
      cache-null-values: false

app:
  shortener:
    base-url: ${APP_SHORTENER_BASE_URL:http://localhost:8080/}